version: '3'
services:
  db:
    image: mysql
    # cap_add:
      # - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=t3-blog
      - MYSQL_ROOT_PASSWORD=admin12345
    ports:
      - '33306:3306'
    # volumes:
      # - db:/var/lib/mysql
      # - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
